name: Patch and Build

on:
  push:
    branches: [ "ver/1.20.4" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Configure Git User Details
        run: git config --global user.email "info@theunrealzaka.me" && git config --global user.name "TheUnrealZaka"
      - name: Apply Patches
        run: ./gradlew applyPatches
      - name: Build
        run: ./gradlew build
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: Folia
          path: build/libs/*
      - name: Release (latest)
        if: github.ref_name == env.branch
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Build #${{ env.workflow }}"
          automatic_release_tag: latest-${{ env.version }}
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: build/libs/*.jar
          prerelease: false
      - name: Release (History)
        if: github.ref_name == env.branch
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Build #${{ env.workflow }}"
          automatic_release_tag: build-${{ env.workflow }}
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: build/libs/*.jar
          prerelease: false